[package]
name = "v-distributed-tunnel-v1"
version = "0.1.0"
edition = "2024"

[dependencies]
quinn = "0.11"
rustls = "0.23"
rustls-pemfile = "2.2.0"
rustls-pki-types = "1.12.0"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
